title: 涂亮 
email: info@tuliang.org
description: "涂亮的个人博客"
baseurl: "/"
url: "alfred-sun.github.io"
username: 'tuliang'
repository: "https://github.com/tuliangblog"
paginate: 10
markdown: kramdown
permalink: :title
pygments: true
safe: true
